# Generated by Django 2.2.10 on 2020-02-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200229_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('id', 'author_name')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('id', 'book_name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('id', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('id', 'chapter_name')},
        ),
    ]
