# Generated by Django 2.2.10 on 2020-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('book', '0004_auto_20200302_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(to='login.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
